### PR TITLE
Multi-Language Per Show now possible

### PR DESCRIPTION
**Pull request by SirSparkles**
Hi @Tetram76, I have implemented these changes in master based on your inspiration. Any chance you can take a look and do some testing?

### CODE REVIEW

**Comment by Tetram76** [comment]
Hi, 
I don't have much free time right now. Thus, I can't promise anything, but I will try to give a... try.

However, don't be surprised if I reject your Pull request, I will sync my master branch instead (because you did push into your master branch too).

**Comment by SirSparkles** [comment]
No worries - Feel free to throw this PR away - just wanted some way to communicate about these changes. I also wanted to confirm I had covered all the changes you had to make

**Comment by Tetram76** [comment]
I did some test this evening (in France :-) ) and here are some feedback:
* it would be nice, if the show was "force refreshed" after a language change
* for now, I'm investigating a problem I have after changing its language: I'm no longer able to edit it as trying to raises an uncatched exception

**Comment by Tetram76** [comment]
for the second point, I identified the problem : #506

**Comment by Tetram76** [comment]
master synced manually

**Pull request closed without merging**
